name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username jonsnow007 --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag app-server:0.${{ github.run_number }}
      - name: Tag the Docker image
        run: docker tag app-server:0.${{ github.run_number }} jonsnow007/app-server:0.${{ github.run_number }}
      - name: Push the Docker image
        run: docker push jonsnow007/app-server:0.${{ github.run_number }}
